# Generated by Django 4.2.23 on 2025-10-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
