# Generated by Django 4.2.23 on 2025-08-23 07:59

import django.core.validators
from django.db import migrations, models
import s3direct.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', s3direct.fields.S3DirectField(blank=True)),
                ('email', models.CharField(max_length=60)),
                ('type', models.CharField(choices=[('ADMIN', 'ADMIN'), ('USER', 'USER')], max_length=15)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('telnumber', models.CharField(blank=True, max_length=40, null=True)),
                ('password', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(6)])),
                ('active_notification', models.BooleanField(default=True)),
                ('udid', models.CharField(blank=True, max_length=64, null=True)),
                ('login_date', models.DateTimeField(blank=True, null=True)),
                ('is_valid_email', models.BooleanField(blank=True, default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expo_push_token', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'member',
                'ordering': ('-id',),
                'managed': True,
                'unique_together': {('email', 'type')},
            },
        ),
    ]
