# Generated by Django 4.2.16 on 2025-09-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='expo_push_token',
        ),
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
