# Generated by Django 4.2.16 on 2025-09-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_remove_member_expo_push_token_alter_member_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
