# Generated by Django 4.2.23 on 2025-10-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_alter_member_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='member',
            name='is_google_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
