# Generated by Django 4.2.23 on 2025-11-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_member_google_id_member_is_google_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('T_SHIRT', 'T-shirt'), ('PANTALON', 'Pantalon'), ('ROBE', 'Robe'), ('CHAUSSURE', 'Chaussure'), ('VESTE', 'Veste'), ('ELECTRONIQUE', 'Électronique'), ('ACCESSOIRES', 'Accessoires')], max_length=50, unique=True)),
            ],
            options={
                'db_table': 'preference',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='member',
            name='preferences',
            field=models.ManyToManyField(blank=True, related_name='members', to='member.preference'),
        ),
    ]
