# Generated by Django 4.2.16 on 2025-08-29 11:24

from django.db import migrations, models
import django.db.models.deletion
import s3direct.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('image', s3direct.fields.S3DirectField(blank=True)),
                ('type', models.CharField(choices=[('DONATION', 'DONATION'), ('SALE', 'SALE')], max_length=15)),
                ('description', models.CharField(max_length=128)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='member.member')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_products', to='member.member')),
            ],
            options={
                'db_table': 'product',
                'ordering': ('-id',),
                'managed': True,
            },
        ),
    ]
