# Generated by Django 4.2.16 on 2025-09-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('T_SHIRT', 'T_SHIRT'), ('PANTALON', 'PANTALON'), ('ROBE', 'ROBE'), ('CHAUSSURE', 'CHAUSSURE'), ('VESTE', 'VESTE')], default='DONATION', max_length=15),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
