# Generated by Django 4.2.16 on 2025-09-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_adresse_product_category_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='adresse',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
