# Generated by Django 4.2.23 on 2025-10-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('DONATION', 'DONATION'), ('SALE', 'SALE'), ('EXCHANGE', 'EXCHANGE')], max_length=15),
        ),
    ]
