# Generated by Django 4.2.23 on 2025-10-06 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='images',
            new_name='imagess',
        ),
    ]
