# Generated by Django 4.2.23 on 2025-10-06 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_images_product_imagess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='imagess',
            new_name='images',
        ),
    ]
