# Generated by Django 4.2.23 on 2025-10-06 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_product_image'),
    ]

    operations = [
    ]
