# Generated by Django 4.2.23 on 2025-10-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mots_cles_recherches',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
