# Generated by Django 4.2.23 on 2025-10-06 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_mots_cles_recherches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
