# Generated by Django 4.2.23 on 2025-10-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_remove_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('DONATION', 'DONATION'), ('SALE', 'SALE'), ('ECHANGE', 'ECHANGE')], max_length=15),
        ),
    ]
