# Generated by Django 4.2.23 on 2025-10-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('T_SHIRT', 'T_SHIRT'), ('PANTALON', 'PANTALON'), ('ROBE', 'ROBE'), ('CHAUSSURE', 'CHAUSSURE'), ('VESTE', 'VESTE')], default='T_SHIRT', max_length=15),
        ),
    ]
