# Generated by Django 4.2.23 on 2025-11-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('T_SHIRT', 'T_SHIRT'), ('PANTALON', 'PANTALON'), ('ROBE', 'ROBE'), ('CHAUSSURE', 'CHAUSSURE'), ('VESTE', 'VESTE'), ('ELECTRONIQUE', 'ELECTRONIQUE'), ('ACCESSOIRES', 'ACCESSOIRES')], default='T_SHIRT', max_length=15),
        ),
    ]
