# Generated by Django 4.2.23 on 2025-11-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
